#' assignments on 8 data files
#'
#' A dataset containing SMIRFE assignments for 8 samples.
#'
#' @format a list with 8 entries, each of which has:
#' \describe{
#'   \item{tic}{the total intensity of peaks in the spectrum}
#'   \item{assignments}{a data.frame of assignments}
#'   \item{sample}{which sample the assignment are from}
#' }
#'
#' @source generated by `read_smirfe_assignments` on 8 sample files.
"assigned_data"